---
title: "Example Usage of EmPoissonMixtureClustering"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(PoissonMixtureClustering)
# Generate synthetic data
set.seed(500)
n_samples <- 1000
n_clusters <- 4
cluster_centers <- matrix(c(1, 1, 50, 50, 100, 100,200,200), ncol = 2, byrow = TRUE)
X <- rbind(mapply(rpois, n_samples/n_clusters, as.data.frame(cluster_centers)))

# Fit Poisson mixture model
num_clusters_range <- 1:10
fit_result <- fit_poisson_mixture(X, num_clusters_range)
best_num_clusters <- fit_result$best_num_clusters
best_model <- fit_result$best_model

# Print best number of clusters
print(best_num_clusters)

# Plot clustered data
plot_clustered_data(X, best_model)

# Plot BIC vs. number of clusters
plot_bic_vs_num_clusters(num_clusters_range, fit_result$bics)

# Print BIC values for each number of clusters tested
print(data.frame(Number_of_Clusters = num_clusters_range, BIC_Values = fit_result$bics))

# Print cluster numbers of each individual
print("Cluster numbers of each individual:")
cluster_numbers <- predict(best_model, X)
print(cluster_numbers)

# Print probabilities of belonging to each cluster for each individual
print("Probabilities of belonging to each cluster for each individual:")
cluster_probabilities <- e_step(best_model, X)
print(cluster_probabilities)

# Print number of clusters selected
print("Number of clusters selected:")
print(best_num_clusters)

# Print cluster probabilities
print("Cluster probabilities:")
print(best_model$cluster_probs)

# Print cluster lambdas
print("Cluster lambdas:")
print(best_model$cluster_lambdas)
